client:
  image: "rex_client:latest"
  container_name: "rex-client"
  working_dir: "/iprice/rex/client"
  hostname: "client"
  ports:
    - "80:80"
  volumes:
    - "./../client:/iprice/rex/client"
  command: "/bin/bash -c 'nginx -g \"daemon off;\"'"
  restart: "always"

api:
  image: "rex_api:latest"
  container_name: "rex-api"
  working_dir: "/iprice/rex/api"
  hostname: "api"
  ports:
    - "8008:80"
  volumes:
    - "./../api:/iprice/rex/api"
  command: "/bin/bash -c '/etc/init.d/php7.0-fpm start; /usr/sbin/nginx'"
  restart: "always"
